### ISSUE TITLE
Ошибка чтения PublicKey

### ISSUE THREAD

**Issue by HardKot** [Tinkoff/AcquiringSdk_IOS#127]
### Описание бага
> The operation couldn’t be completed. (TinkoffASDKCore.AcquiringSdkError error 0.)The operation couldn’t be completed. (TinkoffASDKCore.AcquiringSdkError error 0.)
### После каких действий возникает ошибка
> При попытке построить мост с React-Native. В других случаях не проверял

    private func initSDK(TerminalKey: String, PublicKey: String) -> Void {
        print("Создаю данные для sdk")
        let credentional = AcquiringSdkCredential(terminalKey: TerminalKey, publicKey: PublicKey);
        let configuration = AcquiringSdkConfiguration(credential: credentional);
        configuration.logger = AcquiringLoggerDefault.init()
        do {
            print("Создаю sdk")
            let sdk = try AcquiringUISDK.init(configuration: configuration)
            print("SDK создан")
            self.sdk = sdk
        } catch {
            print(error.localizedDescription, error)
            rejecterTriger("error", "initSDK", error)
        }
    }

### Ожидаемое поведение
> получение объекта от AcquiringUISDK.init

### Что происходит на деле
>ошибка чтения публичного ключа

### Логи
> 
    Создаю данные для sdk
    Создаю sdk
    The operation couldn’t be completed. (TinkoffASDKCore.AcquiringSdkError error 0.)
    publicKey("MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5Yg3RyEkszggDVMDHCAG zJm0mYpYT53BpasrsKdby8iaWJVACj8ueR0Wj3Tu2BY64HdIoZFvG0v7UqSFztE/zUvnznbXVYguaUcnRdwao9gLUQO2I/097SHF9r++BYI0t6EtbbcWbfi755A1EWfu9tdZYXTrwkqgU9ok2UIZCPZ4evVDEzDCKH6ArphVc4+iKFrzdwbFBmPmwi5Xd6CB9Na2kRoPYBHePGzGgYmtKgKMNs+6rdv5v9VB3k7CS/lSIH4p74/OPRjyryo6Q7NbL+evz0+s60Qz5gbBRGfqCA57lUiB3hfXQZq5/q1YkABOHf9cR6Ov5nTRSOnjORgPjwIDAQAB")

**Comment by ElfenLiedGH** [comment]
> ### Описание бага
> > The operation couldn’t be completed. (TinkoffASDKCore.AcquiringSdkError error 0.)The operation couldn’t be completed. (TinkoffASDKCore.AcquiringSdkError error 0.)
> 
> ### После каких действий возникает ошибка
> > При попытке построить мост с React-Native. В других случаях не проверял
> 
> ```
> private func initSDK(TerminalKey: String, PublicKey: String) -> Void {
>     print("Создаю данные для sdk")
>     let credentional = AcquiringSdkCredential(terminalKey: TerminalKey, publicKey: PublicKey);
>     let configuration = AcquiringSdkConfiguration(credential: credentional);
>     configuration.logger = AcquiringLoggerDefault.init()
>     do {
>         print("Создаю sdk")
>         let sdk = try AcquiringUISDK.init(configuration: configuration)
>         print("SDK создан")
>         self.sdk = sdk
>     } catch {
>         print(error.localizedDescription, error)
>         rejecterTriger("error", "initSDK", error)
>     }
> }
> ```
> 
> ### Ожидаемое поведение
> > получение объекта от AcquiringUISDK.init
> 
> ### Что происходит на деле
> > ошибка чтения публичного ключа
> 
> ### Логи
> > 
> 
> ```
> Создаю данные для sdk
> Создаю sdk
> The operation couldn’t be completed. (TinkoffASDKCore.AcquiringSdkError error 0.)
> publicKey("MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5Yg3RyEkszggDVMDHCAG zJm0mYpYT53BpasrsKdby8iaWJVACj8ueR0Wj3Tu2BY64HdIoZFvG0v7UqSFztE/zUvnznbXVYguaUcnRdwao9gLUQO2I/097SHF9r++BYI0t6EtbbcWbfi755A1EWfu9tdZYXTrwkqgU9ok2UIZCPZ4evVDEzDCKH6ArphVc4+iKFrzdwbFBmPmwi5Xd6CB9Na2kRoPYBHePGzGgYmtKgKMNs+6rdv5v9VB3k7CS/lSIH4p74/OPRjyryo6Q7NbL+evz0+s60Qz5gbBRGfqCA57lUiB3hfXQZq5/q1YkABOHf9cR6Ov5nTRSOnjORgPjwIDAQAB")
> ```

у тебя паблик кей кривой просто

**Comment by ElfenLiedGH** [comment]
@HardKot Получилось IOS прикрутить? у меня крашится

**Comment by HardKot** [comment]
@ElfenLiedGH с публичным ключом разобрался, но теперь просто выдает 403 ошибку.. Но чтобы исключить момент с проблемами terminalKey и PublicKey нужно проверить их на android... Но чет не особо руки доходят

**Comment by ElfenLiedGH** [comment]
@ElfenLiedGH если тестовые сервера пытаешься, то они не пашут, надо тестовый терминал из лк

**Comment by HardKot** [comment]
@ElfenLiedGH в том то и прикол что ни тестовый ни боевой(режим тоже поменял) из лк 403 возвращает. Хотя на android в приложеии было все ок(но хочу на всякий случай перепроверить)
