### ISSUE TITLE
Оплата не проходит - ошибка "Поле Token не должно быть пустым."

### ISSUE THREAD

**Issue by starikovvm** [Tinkoff/AcquiringSdk_IOS#162]
### Описание бага
При оплате приходит ошибка: Неверные параметры. Поле Token не должно быть пустым. Code=9999 "(null)" UserInfo={Success=false, PaymentId=null, Amount=null, Status=null, Message=Неверные параметры., OrderId=null, Details=Поле Token не должно быть пустым., ErrorCode=9999, TerminalKey=null}

В прошлых версиях SDK при создании запроса на оплату удалили функционал формирования Token. В дальнейшем мы обсуждали с поддержкой, что токен стоит вернуть в SDK, так как его отсутствие отрицательно влияет на безопасность. Как сейчас видим, SDK не генерирует токен, но тестовая и прод среды  его требуют.

### После каких действий возникает ошибка
После ввода данных карты или получения привязанных карт

### Ожидаемое поведение
Оплата должна проходить

### Что происходит на деле
Приходит ошибка

### Видео процесса возникновение ошибки/демонстрационный проект.
Запросы, пойманные через прокси:
<img width="1771" alt="Снимок экрана 2022-09-07 в 15 09 39" src="https://user-images.githubusercontent.com/6888015/188880560-f79aff68-f9ef-416b-8051-4bfe4a047c5d.png">
<img width="1771" alt="Снимок экрана 2022-09-07 в 15 09 41" src="https://user-images.githubusercontent.com/6888015/188880612-7000a0e2-178c-486f-b690-6df9e903b17d.png">

### Окружение и настройки:

- **Версия компонента:** TinkoffASDK 2.10.1
- **Версия iOS:** iOS 15
- **Версия Xcode:** Xcode 13
- **Версия Swift:** Swift 5.2
- **Используемый девайс/симулятор:** iPhone 13

**Comment by starikovvm** [comment]
Разобрались через саппорт:

> У терминала сменился connection_type
> Был mobile_sdk,а стал http
> В нашей админке нет типа подключения MOBILE_SDK
> Там указан http. При обновлении урлов слетел тип подключения и мы получили проблему.
> Админку сейчас пилят новую, обещают к концу года.
> Это с одной стороны хорошо, а с другой стороны нам сейчас не добавят в старую админку новый тип подключения, так что есть вероятность повторения проблемы

Есть какие-то сроки, когда планируется поддержать Token в SDK?
И создание оплаты (чека) не на клиенте, при использовании SDK тоже хотелось бы увидеть.

**Comment by akhaman** [comment]
Исправлено в версии [2.12.2](https://github.com/Tinkoff/AcquiringSdk_IOS/releases/tag/2.12.2)
[Предоставление токена для подписи запроса](https://github.com/Tinkoff/AcquiringSdk_IOS#предоставление-токена-для-подписи-запросов)
