### ISSUE TITLE
Проблема при билде  

### ISSUE THREAD

**Issue by serg8419** [Tinkoff/AcquiringSdk_IOS#169]
<img width="1437" alt="CleanShot 2022-09-13 at 17 02 54@2x" src="https://user-images.githubusercontent.com/80505359/189908938-7ba36bc0-0b30-4ee3-9451-d9d2a563b30c.png">

- **Версия Xcode:** [Xcode 14]
Компилятор не может переварить выражение 
var origin = (collectionView.bounds.width + evaluatedSectionInset.left - evaluatedSectionInset.right - group.reduce(0) { $0 + $1.frame.size.width } - CGFloat(group.count - 1) * evaluatedMinimumInteritemSpacing) / 2

**Comment by alkozin** [comment]
В лоб решается разбиением на строки. 

`var origin = 
origin -= 
origin /= 2 `

Можете поправить? Там в обоих местах один и тот же код.
