### ISSUE TITLE
Не работает СБП после обновления на iOS 16

### ISSUE THREAD

**Issue by edementiev** [Tinkoff/AcquiringSdk_IOS#174]
### Описание бага
До обновления на iOS 16 платежи через СПБ работали нормально
После обновления и сборки проекта с поддержкой iOS 16 при нажатии на кнопку СПБ происходить переход на главную страницу Банковского приложения Тиньков и на этом все

iOS 16
iPhone 12 Pro Max

**Comment by ivanglushko** [comment]
Пока выяснияем причины в сдк или мб. Позже дадим ответ.

**Comment by akhaman** [comment]
Привет! Если не сложно прикрепи пожалуйста скринкаст с проблемой. Передадим коллегам из приложения

**Comment by edementiev** [comment]
Платежи через tinkoff-pay работают без проблем

**Comment by edementiev** [comment]
> Привет! Если не сложно прикрепи пожалуйста скринкаст с проблемой. Передадим коллегам из приложения
Удалось ли получить какой то ответ от коллег?
Так до сиз пор и не работает функционал платежей СБП

**Comment by VNGXR** [comment]
Если не ошибаюсь, у нас проблема решилась добавлением **bank100000000004** в **LSApplicationQueriesSchemes** (раньше работало и с **tinkoffbank**)

**Comment by edementiev** [comment]
> Если не ошибаюсь, у нас проблема решилась добавлением **bank100000000004** в **LSApplicationQueriesSchemes** (раньше работало и с **tinkoffbank**)

Цифры 100000000004 уникальны для каждого отдельного клиента? Или одинаково для всех?

**Comment by akhaman** [comment]
`bank100000000004` это и подобные значения уникальны для каждого банковского приложения. 
Здесь логика следующая:

ASDK делает запрос в национальную платежную систему  и получает список банков, поддерживающих СБП:
https://qr.nspk.ru/proxyapp/c2bmembers.json

Далее на основе параметра `schema` из ответа и линка, присылаемого нам из API эквайринга в методе `GetQr` формируется диплинк в виде:
`bank100000000004:\\{линк, полученный из GetQr}`

По всей видимости эти схемы изменились в нспк, поэтому возникла такая проблема
