### ISSUE TITLE
Ошибки сборки после обновления pods

### ISSUE THREAD

**Issue by alkozin** [Tinkoff/AcquiringSdk_IOS#184]
### Описание бага
После обновления pods необходимо настраивать проект для установки.

### После каких действий возникает ошибка
pod update

### Ожидаемое поведение
Проект продолжает собираться без ошибок

### Что происходит на деле
Ошибка подписитаргетов 'TinkoffASDKCore-TinkoffASDKCoreResources', 'TinkoffASDKUI-TinkoffASDKUIResources'

### Логи
.../Pods/Pods.xcodeproj error project: Signing for "TinkoffASDKCore-TinkoffASDKCoreResources" requires a development team. Select a development team in the Signing & Capabilities editor.
.../Pods/Pods.xcodeproj error project: Signing for "TinkoffASDKUI-TinkoffASDKUIResources" requires a development team. Select a development team in the Signing & Capabilities editor.

### Видео процесса возникновение ошибки/демонстрационный проект.
<img width="458" alt="Screenshot 2022-09-30 at 15 04 39" src="https://user-images.githubusercontent.com/2376017/193222453-fd9c2867-e4ec-48bb-a4d9-07ed9ac13981.png">

### Окружение и настройки:

- **Версия компонента:** 2.10.4
- **Версия iOS:**  iOS 16.0
- **Версия Xcode:** 14.0.1 (14A400) 
- **Версия Swift:** swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
- **Используемый девайс/симулятор:** iPhone 13

**Comment by ivanglushko** [comment]
Спасибо за хорошо оформленный ишью) Скажите пробовали воспроизвести используя Xcode 13.4 или 13.4.1 ?

**Comment by ivanglushko** [comment]
Задачку пока завел MIC-6541 на неделе постараюсь посмотреть.

**Comment by VNGXR** [comment]
Временное решение в Podfile:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
```

**Comment by ivanglushko** [comment]
Workaround 

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGN_IDENTITY'] = ""
     end
  end
end
```

**Comment by ivanglushko** [comment]
В следующем релизе будет поправлено, пулл реквест -- https://github.com/Tinkoff/AcquiringSdk_IOS/pull/189
