### ISSUE TITLE
При отправке в AppStore получаем предупреждение "App Store Connect Operation Error The app references non-public selectors in Payload/gorbilet.app/Frameworks/TinkoffASDKUI.framework/TinkoffASDKUI: didTapCloseButton"

### ISSUE THREAD

**Issue by edementiev** [Tinkoff/AcquiringSdk_IOS#208]
При публикации в AppStore облучаем предупреждение в xCode

App Store Connect Operation Error
The app references non-public selectors in Payload/gorbilet.app/Frameworks/TinkoffASDKUI.framework/TinkoffASDKUI: didTapCloseButton

Как я понимаю ваш метод по имени совпадает с приватным методом на это xCode и агрится

Далее все проходит нормально, AppStore Connect нормально обрабатывает билд и публикация проходит без проблем, но предупреждение напрягает (

**Comment by akhaman** [comment]
Привет! Ситуация странная на самом деле) Вероятно из-за атрибута objc так ругается
<img width="235" alt="image" src="https://user-images.githubusercontent.com/55531056/198586558-7cefe8c2-6394-4c9b-9cba-d10631aef5b9.png">

Момент не принципиальный, попробуем переименовать
