### ISSUE TITLE
Ошибка сборки fastlane после обновления на версию пакета 2.12.2

### ISSUE THREAD

**Issue by Pluxury** [Tinkoff/AcquiringSdk_IOS#214]
### Описание бага
CI, построенный на fastlane начинает выдавать ошибку после обновления пакетов sdk до версии 2.12.2

```
Pods/TinkoffASDKUI/TinkoffASDKUI/TinkoffASDKUI/SDK/AcquiringUISDK.swift:21:8: no such module 'ThreeDSWrapper'
import ThreeDSWrapper

The following build commands failed:
[15:23:00]: ▸ 	CompileSwift normal arm64 (in target 'TinkoffASDKUI' from project 'Pods')
[15:23:00]: ▸ 	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'TinkoffASDKUI' from project 'Pods')
```

### После каких действий возникает ошибка
Обновить пакеты sdk до версии 2.12.2, используя cocoapods

### Ожидаемое поведение
Build succseed 

### Что происходит на деле
Buidl Failed

### Логи
В логах ошибки следующие: 
```
The following build commands failed:
	CompileSwift normal arm64 (in target 'TinkoffASDKUI' from project 'Pods')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'TinkoffASDKUI' from project 'Pods')
	
	Pods/TinkoffASDKUI/TinkoffASDKUI/TinkoffASDKUI/SDK/AcquiringUISDK.swift:21:8: no such module 'ThreeDSWrapper'
import ThreeDSWrapper
```

### Видео процесса возникновение ошибки/демонстрационный проект.
нет

### Окружение и настройки:

- **Версия компонента:** 2.12.2
- **Версия iOS:** iOS 15
- **Версия Xcode:** Xcode 13.4.1
- **Версия Swift:** Swift 5.2

**Comment by ivanglushko** [comment]
Попробовал на пустом проекте собрать 2.12.2 используя Xcode 13.4.1 
В итоге успех. Пока не могу воспроизвести.

Может есть какие либо вводные еще?

Что можно попробовать сейчас: 
Почистить Derived Data
Повторно прогнать сборку. 
---
<img width="1242" alt="Screenshot 2022-11-07 at 17 15 00" src="https://user-images.githubusercontent.com/36343782/200320173-3b06203a-1b88-45bb-9f92-b32a872cc766.png">

**Comment by Pluxury** [comment]
Удивительно, но локально тоже успешно собираю. Проблема конкретно на машине build agent

**Comment by ivanglushko** [comment]
Попробуй снести сгенеренный проект (workspace) и запустить pod install либо проделать pod deintegrate && pod install

**Comment by Pluxury** [comment]
@ivanglushko Все базовые способы решения проблем с подами сделал, в том числе обновление самого cocoapods. 
Проблема в чем-то другом. Что странно с tinkoffsdk 2.9.0 все работало отлично, проблема появляется именно после бампа версии пакета до 2.12.0. Полагаю, что аффектят изменения в рамках https://github.com/Tinkoff/AcquiringSdk_IOS/pull/165

**Comment by Pluxury** [comment]
Ох, я не силен в CI и совсем ни к чему было, что локальная сборка через CLI не то же самое. Но мне удалось победить проблему. 
Я обновил свой gemfile следующим образом: 
`gem "cocoapods", ">= 1.11.3"` и выполнил `bundle update `.
Однако, это говорит о том, что в cocoapods есть важное обновление. К слову предыдущая версия у меня была 1.8.4

Думаю, ишью можно закрыть. @ivanglushko благодарю за Ваше потраченное время.

**Comment by ivanglushko** [comment]
@Pluxury Супер, я уже голову ломал что не так) Будем иметь ввиду что такие проблемы, могут возникнуть 👍
