### ISSUE TITLE
СБП GA

### ISSUE THREAD

**Issue by SeAtTink** [Tinkoff/AcquiringSdk_IOS#234]
Добрый день,
Подскажите, есть ли в SDK коллбэк url, чтобы пользователь автоматически возвращался с приложения банка после оплаты ?

**Comment by akhaman** [comment]
Добрый день! 
Есть такая возможность. Для этого в `PaymentInitData` необходимо передать параметры `successURL` и `failURL`

https://github.com/Tinkoff/AcquiringSdk_IOS#оплата-с-инициацией-платежа

**Comment by VNGXR** [comment]
> Добрый день! Есть такая возможность. Для этого в `PaymentInitData` необходимо передать параметры `successURL` и `failURL`
> 
> [https://github.com/Tinkoff/AcquiringSdk_IOS#оплата-с-инициацией-платежа](https://github.com/Tinkoff/AcquiringSdk_IOS#%D0%BE%D0%BF%D0%BB%D0%B0%D1%82%D0%B0-%D1%81-%D0%B8%D0%BD%D0%B8%D1%86%D0%B8%D0%B0%D1%86%D0%B8%D0%B5%D0%B9-%D0%BF%D0%BB%D0%B0%D1%82%D0%B5%D0%B6%D0%B0)

К сожалению, не работает с СБП

**Comment by akhaman** [comment]
Данные, которые вы кладете `PaymentInitData` отправляются в запросе `v2/Init`

Пришлите пожалуйста лог этого запроса и ответа

**Comment by VNGXR** [comment]
> Данные, которые вы кладете `PaymentInitData`, отправляются в запросе `v2/Init`
> 
> Пришлите пожалуйста лог этого запроса и ответа
Реквест:
```
{
    "Amount": 8700,
    "CustomerKey": "+7 (952) 600-22-68",
    "DATA": {
        "connection_type": "mobile_sdk",
        "device_model": "iPhone13,3",
        "name": "ТЕСТ НЕ ГОТОВИТ",
        "phone": "+7 (952) 600-22-68",
        "sdk_version": "2.13.1",
        "software_version": "16.1.2"
    },
    "Description": "ООО «Гурманика»",
    "FailURL": "https://gurmanika.ru/payment_fail",
    "OrderId": "АЗС30-14/12/22-52845",
    "Receipt": {
        "Customer": "+7 (952) 600-22-68",
        "Email": "mrcrash0811@gmail.com",
        "Items": [
            {
                "Amount": 8700,
                "Name": "Морс вишня-смородина",
                "Price": 8700,
                "Quantity": 1,
                "Tax": "vat20"
            }
        ],
        "Phone": "+7 (952) 600-22-68",
        "Taxation": "osn"
    },
    "SuccessURL": "https://gurmanika.ru/payment_success",
    "TerminalKey": "нашКлюч"
}
```

Респонс:
```
{
    "Amount": 8700,
    "ErrorCode": "0",
    "OrderId": "АЗС30-14/12/22-52845",
    "PaymentId": "2100737338",
    "Status": "NEW",
    "Success": true,
    "TerminalKey": "нашКлюч"
}
```

**Comment by akhaman** [comment]
Спасибо. Передал коллегам

**Comment by akhaman** [comment]
Уточнил информацию. `successURL` и `failURL` фактически используются только при оплате через TinkoffPay. 

Для того, чтобы совершался редирект при оплате по СБП вам необходимо в личном кабинете указать ссылку в графе `сайт`
