### ISSUE TITLE
TinkoffASDKUI не обновляется до 2.13.0

### ISSUE THREAD

**Issue by iamDiNGo** [Tinkoff/AcquiringSdk_IOS#236]
Downloading dependencies
Installing TinkoffASDKCore (2.13.0)
Installing TinkoffASDKUI (2.12.2)
Generating Pods project

[!] CocoaPods could not find compatible versions for pod "TinkoffASDKUI":
  In Podfile:
    TinkoffASDKUI (= 2.13.0)

None of your spec sources contain a spec satisfying the dependency: `TinkoffASDKUI (= 2.13.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Удалял поды и явно указывал 2.13.0 версию, всё равно не видит.

**Comment by akhaman** [comment]
Привет! 
Возникла ошибка на CI, из-за которой релизнулся модуль `TinkoffASDKCore (2.13.0)`, а `TinkoffASDKUI` - нет. 
Проблемку решили, релизнули нормально `2.13.1`
Пропиши в Podfile:

```ruby
 pod 'TinkoffASDKCore', '2.13.1'
  pod 'TinkoffASDKUI', '2.13.1'
```
