### ISSUE TITLE
Выбор предпочитаемой карты для оплаты

### ISSUE THREAD

**Issue by MonsWriter** [Tinkoff/AcquiringSdk_IOS#28]
Здравствуйте! 

Мы используем Tinkoff Acquiring SDK в мобильном приложении для привязки банковских карт и для управления банковскими картами. Привязывать карту мы хотим через приложение, а инициализировать платёж с бэкенда, когда пользователь воспользовался нашей услугой.

Как мы можем для этого определить, какая из привязанных карт является предпочитаемой для оплаты? 

В версии SDK для Android совсем недавно добавили такую возможность: https://github.com/TinkoffCreditSystems/AcquiringSdkAndroid/issues/28#issuecomment-744514085

Есть ли что-то подобное в iOS версии?

**Comment by ivanglushko** [comment]
Привет!
Задача лежит в беклоге на 2023 год. 
Пока не приотизирована и в работу в текущем году не попадет.
Закрываю issue.
