### ISSUE TITLE
Access forbidden

### ISSUE THREAD

**Issue by Liklainy** [Tinkoff/AcquiringSdk_IOS#29]
Здравствуйте,

У одного клиента после ввода данных карты когда должна открыться страница банка выпадает ошибка 403 - Access forbidden
iPhone SE, Версия ПО 14.2, версия sdk 2.0.4

Подскажите, пожалуйста, в чем может быть ошибка?
<details>
<summary>Скрин</summary>

![image](https://user-images.githubusercontent.com/20872986/103203311-ac575200-4905-11eb-8a7b-db8dcc5a8338.png)
</details>

**Comment by muratoffalex** [comment]
Добрый день.
Аналогичная проблема. Обратилось несколько пользователей - не могут совершить оплату с картой МИР агропромкредит банка, ошибка Forbidden. You don't have permission to access this resource. При этом, этот же пользователь говорит, что провёл эксперимент и в нашем приложении на андройде с вашей сдк оплата прошла успешно

<details>
  <summary>Скрин</summary>
  <img src='https://user-images.githubusercontent.com/24474827/115343583-95df4a00-a1c5-11eb-8eab-570d61a70436.jpg'>
</details>

**Comment by ivanglushko** [comment]
Привет! Закрываем за истечением времени, если проблема актуальна, просьба переоткрыть или создать новый issue.
