### ISSUE TITLE
Поле PAN не должно быть пустым. При оплате ApplePay.

### ISSUE THREAD

**Issue by reacct** [Tinkoff/AcquiringSdk_IOS#34]
Добрый день!
При попытке оплаты с помощью ApplePay в ответ на FinishAuthorize приходит:
```
🛬 End request: https://rest-api-test.tcsbank.ru/v2/FinishAuthorize, with response data:
{"Success":false,"ErrorCode":"9999","Message":"Неверные параметры.","Details":"Поле PAN не должно быть пустым."}
```
Используется реальная карта, оплата на тестовом аккаунте.
То же самое возвращает в ASDKSample.

Подскажите, пожалуйста, в какой момент и каким методом нужно устанавливать PAN при оплате через ApplePay.

**UPD**:
Если изменить сервер на продовый (securepay.tinkoff.ru), то приходит ответ:
```
🛬 End request: https://securepay.tinkoff.ru/v2/FinishAuthorize, with response data:
{"Success":false,"ErrorCode":"9999","Message":"Неверные параметры.","Details":"Ошибка шифрования карточных данных."}
```

**Comment by vdugnist** [comment]
Присоединяюсь к вопросу. Прошёлся дебаггером по AcquiringUISDK, apple pay вызывает `paymentAuthorizationViewController(_: ,didAuthorizePayment payment:, completion:) -> Void)`, ошибка приходит после вызова finishAuthorize.

**Comment by reacct** [comment]
На рабочем терминале оплата проходит.
Но вопрос остаётся открытым, потому что много времени на это было потрачено, и неплохо было объяснить из-за чего проблема, что в будущем люди не натыкались.

**Comment by egorshoba** [comment]
Присоединяюсь, такая же проблема

**Comment by vdugnist** [comment]
У меня проблема оказалась в админке. Достаточно было правильно настроить там apple pay.

**Comment by egorshoba** [comment]
А как там настраивать?

**Comment by ivanglushko** [comment]
На данный момент поддержка ApplePay отключена, если проблема повторится, когда вернеться Apple Pay просьба заново открыть issue
