### ISSUE TITLE
Не срабатывает метод cardsListUpdated (CardListDataSourceStatusListener)

### ISSUE THREAD

**Issue by MonsWriter** [Tinkoff/AcquiringSdk_IOS#38]
Раньше вроде бы работало. 
Теперь перестал срабатывать метод, который должен вызываться после закрытия экрана со списком привязанных банковских карт.

<img width="824" alt="Screen Shot 2021-02-01 at 12 44 39" src="https://user-images.githubusercontent.com/1092229/106424009-aff17200-648b-11eb-8961-bf519fce71d2.png">

<img width="860" alt="Screen Shot 2021-02-01 at 12 45 04" src="https://user-images.githubusercontent.com/1092229/106424030-b7188000-648b-11eb-990c-8fbf251dd0c6.png">

Ни при удалении карт, ни при добавлении, ни при закрытии экрана без изменения карт, метод cardsListUpdated не срабатывает.

В примерах ASDKSample в BuyProductsViewController этот метод тоже не срабатывает, если что.

**Comment by grishamsc** [comment]
@MonsWriter спасибо за предоставленный код, посмотрим.
