### ISSUE TITLE
Ошибка при выполнении FinishAuthorize

### ISSUE THREAD

**Issue by iddcud** [Tinkoff/AcquiringSdk_IOS#40]
Здравствуйте! Подскажите пожалуйста, столкнулся со следующей проблемой:

При попытке оплаты картой, сразу после заполнения платежной формы и выполнения метода FinishAuthorize, как в случае c тестовым терминалом, так и c рабочим приходит следующий ответ:
     
    End request: https://rest-api-test.tcsbank.ru/v2/Check3dsVersion, with response data: {"Success":false,"ErrorCode":"9999","Message":"Неверные параметры.","Details":"Неверный номер карты"}

При попытке оплаты с помощью ApplePay (использую свой merchant_id) такой ответ:

    End request: https://securepay.tinkoff.ru/v2/FinishAuthorize, with response data: {"Success":false,"ErrorCode":"4","Message":"Запрашиваемое состояние транзакции является неверным.","Details":"Изменение статуса недопустимо."}

Sdk инициализируется успешно, шифрование данных карты тоже отрабатывает (возвращает CardData).

**Comment by kei-sidorov** [comment]
Сегодня поймал схожую проблему при обновлении со старой SDK на эту версию. Продаршен терминал.

Прохожу 3DS, возвращается подобный ответ:

```
▿ PaymentStatusResponse
  - success : true
  - errorCode : 9999
  ▿ errorMessage : Optional<String>
    - some : "Повторите попытку позже."
  - errorDetails : nil
  ▿ terminalKey : Optional<String>
    - some : ***MY TERMINAL ID***
  - orderId : "9972"
  - paymentId : 700000332840
  - amount : 70
  - status : TinkoffASDKCore.PaymentStatus.unknown
```

**Comment by kei-sidorov** [comment]
Разработчики сделали тестовый сервер — сервером по умолчанию. Меняется про создании инстанса `AcquiringSdkConfiguration`

**Comment by ivanglushko** [comment]
Привет! 
Наблюдается ли проблема сейчас?

**Comment by ivanglushko** [comment]
Закрываем по истечению времени, если проблема актуальна, создавайте новый issue 🙏
