### ISSUE TITLE
isPayWithAppleAvailable returns 0

### ISSUE THREAD

**Issue by HappyCodingLover** [Tinkoff/AcquiringSdk_IOS#61]
`isPayWithAppleAvailable` returns 0 which means fail I believe.
What should I do for this to be success?
I think documentation is missing about this point.
Thanks very much in advance.

**Comment by ivanglushko** [comment]
Hi there! Sorry for not replying for a long time. As for now we don't support Apple Pay. 
But i believe it should be handled on merchant side in their terminal settings.
