### ISSUE TITLE
Библиотека не добавляется в проект

### ISSUE THREAD

**Issue by nikitabudkovskiy** [Tinkoff/AcquiringSdk_IOS#86]
Библиотека не добавляется в проект
![Снимок экрана 2021-07-12 в 11 37 16](https://user-images.githubusercontent.com/7972703/125256933-94757780-e305-11eb-8ee1-0df838e4902f.png)
`https://github.com/TinkoffCreditSystems/AcquiringSdk_IOS has no Package.swift manifest in `

**Comment by grishamsc** [comment]
@nikitabudkovskiy 
Здравствуйте. На данный момент еще нет поддержки менеджера зависимостей SPM. В планах ее добавить.

**Comment by rmurad93** [comment]
Я давно отказался от CocoaPods в пользу SPM. Прошу добавить поддержку SFM, это облегчит работу с вашей библиотекой

**Comment by ivanglushko** [comment]
В версии [2.11.0](https://github.com/Tinkoff/AcquiringSdk_IOS/releases/tag/2.11.0) добавлена поддержка SPM, в ридми описан метод интеграции через спм.
