### ISSUE TITLE
Код результата в WebView после оплаты сбербанк. 

### ISSUE THREAD

**Issue by AlekseyPakAA** [Tinkoff/AcquiringSdk_IOS#89]
При оплате картой сбербанка отображается ответ в web view см скриншот
<img width="357" alt="Снимок экрана 2021-08-23 в 13 34 46" src="https://user-images.githubusercontent.com/16940133/130433723-d2f70cdb-2926-4278-830c-71b2f3a5651c.png">

**Comment by NikKovIos** [comment]
Ап

**Comment by ivanglushko** [comment]
Привет!
Актуальна ли проблема сейчас?

**Comment by ivanglushko** [comment]
Закрываем по истечению времени, если проблема актуальна, создавайте новый issue 🙏
