### ISSUE TITLE
Кнопка "Отменить оплату"

### ISSUE THREAD

**Issue by ridbrain** [Tinkoff/AcquiringSdk_IOS#91]
Когда скрыт NavigationBar у NavigationController'a и ты вызываешь оплату, то при нажатие на поле ввода карты, View открывается на весь экран без возможности его потом скрыть, если передумал платить. Надо бы добавить на экран оплаты кнопку "Отменить оплату" или "Назад". На крайний случай можно экран оплаты просто не разворачивать на весь экран, как это сделано у Вас в Android SDK.

**Comment by ALutenko** [comment]
там кнопка есть "назад" в навигейшене, просто на белом фоне она тоже белая. на темной теме ее видно.

**Comment by ivanglushko** [comment]
<img width="358" alt="Screenshot 2022-11-08 at 17 21 50" src="https://user-images.githubusercontent.com/36343782/200575654-439b106d-9898-462d-b0c0-3c50f0952581.png">
Если я правильно понял, то на последней версии сдк, не наблюдаю такой проблемы.

Закрываю по истечении времени, если проблема все таки повторяется и имеется на стороне сдк, просьба открыть новый  issue и заполнить его чтобы максимально понимать суть бага.
