### ISSUE TITLE
React-native

### ISSUE THREAD

**Issue by bondarenkovladislav** [Tinkoff/AcquiringSdk_IOS#96]
Здравствуйте, есть ли возможность использовать с react-native?

**Comment by pistonsky** [comment]
Вот сижу пытаюсь сделать нативный модуль

**Comment by HardKot** [comment]
@pistonsky, Здраствуйте хотел бы узнать об Вашей работе над модулем. Можно ли посмотреть/использовать Ваш код/наработки, Тоже сижу пытаюсь делать.

**Comment by pistonsky** [comment]
Наработки пока слишком сырые, мы решили довольствоваться переходами по ссылкам, которые выдаёт наш backend. Но даже это ещё в работе и поделиться прямо-таки нечем. @HardKot

**Comment by ElfenLiedGH** [comment]
@HardKot простую оплату победил на андроид, на ios пока в процессе из за ужасной документации

**Comment by HardKot** [comment]
У меня есть в планах попробовать сделать мост, но прикол в том что мои знания Java и Swift на уровне нуль

**Comment by ElfenLiedGH** [comment]
@HardKot java https://gist.github.com/ElfenLiedGH/8460d0c302afd645f0999a5cb8c91e84

**Comment by ElfenLiedGH** [comment]
@pistonsky @HardKot ios получилось у кого нибудь прикрутить?

**Comment by ElfenLiedGH** [comment]
@ivanglushko это не может быть пром, т.к. это по сути отдельная библиотека на другом ЯП.

`ЗЫ: если у кого то не получается, пишите, победил нейтив, приложение в проде несколько месяцев.`
