### ISSUE TITLE
Оплата в $ или в другой иностранной валюте

### ISSUE THREAD

**Issue by NikKovIos** [Tinkoff/AcquiringSdk_IOS#97]
Добрый день. Вопрос такой - поддерживается ли оплата в иностранной валюте? 

В SDK указано, что есть поле currency.
Здесь есть обсуждение на эту тему На этих экранах у нас покупки происходят через https://github.com/TinkoffCreditSystems
Этот SDK поддерживает указание валюты. В документации написано:

**Currency**
Код валюты ISO 4217 (например, 643).
Если передан Currency, и он разрешен
для Продавца, то транзакция будет
инициирована в переданной валюте.
Иначе будет использована валюта по
умолчанию для данного терминала
Источник: https://acdn.tinkoff.ru/static/acquiring/5fe98aaa-ec9c-48ff-bcfb-abc2b71d4ee2.pdf

На гитхабе поддержка написала:
Здравствуйте, SDK поддерживает только рубли. При использовании методов на сервере, вы можете указать любую валюту, но списания будут в рублях. 
https://github.com/TinkoffCreditSystems/AcquiringSdk_IOS/issues/18

Мы в приложении хотим внедрить поддержку $. Как-то возможно это сделать с помощью этой sdk?

**Comment by ivanglushko** [comment]
К сожалению, на данный момент доступна оплата только в рублях, поддержка валют не планируется.
